import { LetterData } from './types';

export const ARABIC_LETTERS: LetterData[] = [
  {
    id: 'alif',
    char: 'ا',
    name: 'ألف',
    forms: { isolated: 'ا', start: 'ا', middle: 'ـا', end: 'ـا' },
    sounds: { fatha: 'أَ', kasra: 'إِ', damma: 'أُ' },
    madood: { alif: 'آ', waw: 'أُو', yaa: 'إِي' },
    exampleWord: 'أسد',
    emoji: '🦁',
    sunOrMoon: 'moon',
    wordWithAl: 'الْأَسَد'
  },
  {
    id: 'baa',
    char: 'ب',
    name: 'باء',
    forms: { isolated: 'ب', start: 'بـ', middle: 'ـبـ', end: 'ـب' },
    sounds: { fatha: 'بَ', kasra: 'بِ', damma: 'بُ' },
    madood: { alif: 'بَا', waw: 'بُو', yaa: 'بِي' },
    exampleWord: 'بطة',
    emoji: '🦆',
    sunOrMoon: 'moon',
    wordWithAl: 'الْبَطَّة'
  },
  {
    id: 'taa',
    char: 'ت',
    name: 'تاء',
    forms: { isolated: 'ت', start: 'تـ', middle: 'ـتـ', end: 'ـت' },
    sounds: { fatha: 'تَ', kasra: 'تِ', damma: 'تُ' },
    madood: { alif: 'تَا', waw: 'تُو', yaa: 'تِي' },
    exampleWord: 'تفاحة',
    emoji: '🍎',
    sunOrMoon: 'sun',
    wordWithAl: 'التُّفَاحَة'
  },
  {
    id: 'thaa',
    char: 'ث',
    name: 'ثاء',
    forms: { isolated: 'ث', start: 'ثـ', middle: 'ـثـ', end: 'ـث' },
    sounds: { fatha: 'ثَ', kasra: 'ثِ', damma: 'ثُ' },
    madood: { alif: 'ثَا', waw: 'ثُو', yaa: 'ثِي' },
    exampleWord: 'ثعلب',
    emoji: '🦊',
    sunOrMoon: 'sun',
    wordWithAl: 'الثَّعْلَب'
  },
  {
    id: 'jeem',
    char: 'ج',
    name: 'جيم',
    forms: { isolated: 'ج', start: 'جـ', middle: 'ـجـ', end: 'ـج' },
    sounds: { fatha: 'جَ', kasra: 'جِ', damma: 'جُ' },
    madood: { alif: 'جَا', waw: 'جُو', yaa: 'جِي' },
    exampleWord: 'جمل',
    emoji: '🐪',
    sunOrMoon: 'moon',
    wordWithAl: 'الْجَمَل'
  },
  {
    id: 'haa',
    char: 'ح',
    name: 'حاء',
    forms: { isolated: 'ح', start: 'حـ', middle: 'ـحـ', end: 'ـح' },
    sounds: { fatha: 'حَ', kasra: 'حِ', damma: 'حُ' },
    madood: { alif: 'حَا', waw: 'حُو', yaa: 'حِي' },
    exampleWord: 'حصان',
    emoji: '🐎',
    sunOrMoon: 'moon',
    wordWithAl: 'الْحِصَان'
  },
  {
    id: 'khaa',
    char: 'خ',
    name: 'خاء',
    forms: { isolated: 'خ', start: 'خـ', middle: 'ـخـ', end: 'ـخ' },
    sounds: { fatha: 'خَ', kasra: 'خِ', damma: 'خُ' },
    madood: { alif: 'خَا', waw: 'خُو', yaa: 'خِي' },
    exampleWord: 'خروف',
    emoji: '🐑',
    sunOrMoon: 'moon',
    wordWithAl: 'الْخَرُوف'
  },
  {
    id: 'dal',
    char: 'د',
    name: 'دال',
    forms: { isolated: 'د', start: 'د', middle: 'ـد', end: 'ـد' },
    sounds: { fatha: 'دَ', kasra: 'دِ', damma: 'دُ' },
    madood: { alif: 'دَا', waw: 'دُو', yaa: 'دِي' },
    exampleWord: 'دب',
    emoji: '🐻',
    sunOrMoon: 'sun',
    wordWithAl: 'الدُّب'
  },
  {
    id: 'thal',
    char: 'ذ',
    name: 'ذال',
    forms: { isolated: 'ذ', start: 'ذ', middle: 'ـذ', end: 'ـذ' },
    sounds: { fatha: 'ذَ', kasra: 'ذِ', damma: 'ذُ' },
    madood: { alif: 'ذَا', waw: 'ذُو', yaa: 'ذِي' },
    exampleWord: 'ذرة',
    emoji: '🌽',
    sunOrMoon: 'sun',
    wordWithAl: 'الذُّرَة'
  },
  {
    id: 'raa',
    char: 'ر',
    name: 'راء',
    forms: { isolated: 'ر', start: 'ر', middle: 'ـر', end: 'ـر' },
    sounds: { fatha: 'رَ', kasra: 'رِ', damma: 'رُ' },
    madood: { alif: 'رَا', waw: 'رُو', yaa: 'رِي' },
    exampleWord: 'رمان',
    emoji: '🍎',
    sunOrMoon: 'sun',
    wordWithAl: 'الرُّمَّان'
  },
  {
    id: 'zay',
    char: 'ز',
    name: 'زاي',
    forms: { isolated: 'ز', start: 'ز', middle: 'ـز', end: 'ـز' },
    sounds: { fatha: 'زَ', kasra: 'زِ', damma: 'زُ' },
    madood: { alif: 'زَا', waw: 'زُو', yaa: 'زِي' },
    exampleWord: 'زرافة',
    emoji: '🦒',
    sunOrMoon: 'sun',
    wordWithAl: 'الزَّرَافَة'
  },
  {
    id: 'seen',
    char: 'س',
    name: 'سين',
    forms: { isolated: 'س', start: 'سـ', middle: 'ـسـ', end: 'ـس' },
    sounds: { fatha: 'سَ', kasra: 'سِ', damma: 'سُ' },
    madood: { alif: 'سَا', waw: 'سُو', yaa: 'سِي' },
    exampleWord: 'سيارة',
    emoji: '🚗',
    sunOrMoon: 'sun',
    wordWithAl: 'السَّيَّارَة'
  },
  {
    id: 'sheen',
    char: 'ش',
    name: 'شين',
    forms: { isolated: 'ش', start: 'شـ', middle: 'ـشـ', end: 'ـش' },
    sounds: { fatha: 'شَ', kasra: 'شِ', damma: 'شُ' },
    madood: { alif: 'شَا', waw: 'شُو', yaa: 'شِي' },
    exampleWord: 'شمس',
    emoji: '☀️',
    sunOrMoon: 'sun',
    wordWithAl: 'الشَّمْس'
  },
  {
    id: 'saad',
    char: 'ص',
    name: 'صاد',
    forms: { isolated: 'ص', start: 'صـ', middle: 'ـصـ', end: 'ـص' },
    sounds: { fatha: 'صَ', kasra: 'صِ', damma: 'صُ' },
    madood: { alif: 'صَا', waw: 'صُو', yaa: 'صِي' },
    exampleWord: 'صاروخ',
    emoji: '🚀',
    sunOrMoon: 'sun',
    wordWithAl: 'الصَّارُوخ'
  },
  {
    id: 'dhaad',
    char: 'ض',
    name: 'ضاد',
    forms: { isolated: 'ض', start: 'ضـ', middle: 'ـضـ', end: 'ـض' },
    sounds: { fatha: 'ضَ', kasra: 'ضِ', damma: 'ضُ' },
    madood: { alif: 'ضَا', waw: 'ضُو', yaa: 'ضِي' },
    exampleWord: 'ضفدع',
    emoji: '🐸',
    sunOrMoon: 'sun',
    wordWithAl: 'الضِّفْدَع'
  },
  {
    id: 'taa_emph',
    char: 'ط',
    name: 'طاء',
    forms: { isolated: 'ط', start: 'طـ', middle: 'ـطـ', end: 'ـط' },
    sounds: { fatha: 'طَ', kasra: 'طِ', damma: 'طُ' },
    madood: { alif: 'طَا', waw: 'طُو', yaa: 'طِي' },
    exampleWord: 'طائرة',
    emoji: '✈️',
    sunOrMoon: 'sun',
    wordWithAl: 'الطَّائِرَة'
  },
  {
    id: 'dhaa_emph',
    char: 'ظ',
    name: 'ظاء',
    forms: { isolated: 'ظ', start: 'ظـ', middle: 'ـظـ', end: 'ـظ' },
    sounds: { fatha: 'ظَ', kasra: 'ظِ', damma: 'ظُ' },
    madood: { alif: 'ظَا', waw: 'ظُو', yaa: 'ظِي' },
    exampleWord: 'ظرف',
    emoji: '✉️',
    sunOrMoon: 'sun',
    wordWithAl: 'الظَّرْف'
  },
  {
    id: 'ain',
    char: 'ع',
    name: 'عين',
    forms: { isolated: 'ع', start: 'عـ', middle: 'ـعـ', end: 'ـع' },
    sounds: { fatha: 'عَ', kasra: 'عِ', damma: 'عُ' },
    madood: { alif: 'عَا', waw: 'عُو', yaa: 'عِي' },
    exampleWord: 'عنب',
    emoji: '🍇',
    sunOrMoon: 'moon',
    wordWithAl: 'الْعِنَب'
  },
  {
    id: 'ghain',
    char: 'غ',
    name: 'غين',
    forms: { isolated: 'غ', start: 'غـ', middle: 'ـغـ', end: 'ـغ' },
    sounds: { fatha: 'غَ', kasra: 'غِ', damma: 'غُ' },
    madood: { alif: 'غَا', waw: 'غُو', yaa: 'غِي' },
    exampleWord: 'غزالة',
    emoji: '🦌',
    sunOrMoon: 'moon',
    wordWithAl: 'الْغَزَالَة'
  },
  {
    id: 'faa',
    char: 'ف',
    name: 'فاء',
    forms: { isolated: 'ف', start: 'فـ', middle: 'ـفـ', end: 'ـف' },
    sounds: { fatha: 'فَ', kasra: 'فِ', damma: 'فُ' },
    madood: { alif: 'فَا', waw: 'فُو', yaa: 'فِي' },
    exampleWord: 'فراشة',
    emoji: '🦋',
    sunOrMoon: 'moon',
    wordWithAl: 'الْفَرَاشَة'
  },
  {
    id: 'qaaf',
    char: 'ق',
    name: 'قاف',
    forms: { isolated: 'ق', start: 'قـ', middle: 'ـقـ', end: 'ـق' },
    sounds: { fatha: 'قَ', kasra: 'قِ', damma: 'قُ' },
    madood: { alif: 'قَا', waw: 'قُو', yaa: 'قِي' },
    exampleWord: 'قلم',
    emoji: '🖊️',
    sunOrMoon: 'moon',
    wordWithAl: 'الْقَلَم'
  },
  {
    id: 'kaaf',
    char: 'ك',
    name: 'كاف',
    forms: { isolated: 'ك', start: 'كـ', middle: 'ـكـ', end: 'ـك' },
    sounds: { fatha: 'كَ', kasra: 'كِ', damma: 'كُ' },
    madood: { alif: 'كَا', waw: 'كُو', yaa: 'كِي' },
    exampleWord: 'كتاب',
    emoji: '📖',
    sunOrMoon: 'moon',
    wordWithAl: 'الْكِتَاب'
  },
  {
    id: 'lam',
    char: 'ل',
    name: 'لام',
    forms: { isolated: 'ل', start: 'لـ', middle: 'ـلـ', end: 'ـل' },
    sounds: { fatha: 'لَ', kasra: 'لِ', damma: 'لُ' },
    madood: { alif: 'لَا', waw: 'لُو', yaa: 'لِي' },
    exampleWord: 'ليمون',
    emoji: '🍋',
    sunOrMoon: 'sun',
    wordWithAl: 'اللَّيْمُون'
  },
  {
    id: 'meem',
    char: 'م',
    name: 'ميم',
    forms: { isolated: 'م', start: 'مـ', middle: 'ـمـ', end: 'ـم' },
    sounds: { fatha: 'مَ', kasra: 'مِ', damma: 'مُ' },
    madood: { alif: 'مَا', waw: 'مُو', yaa: 'مِي' },
    exampleWord: 'موز',
    emoji: '🍌',
    sunOrMoon: 'moon',
    wordWithAl: 'الْمَوْز'
  },
  {
    id: 'noon',
    char: 'ن',
    name: 'نون',
    forms: { isolated: 'ن', start: 'نـ', middle: 'ـنـ', end: 'ـن' },
    sounds: { fatha: 'نَ', kasra: 'نِ', damma: 'نُ' },
    madood: { alif: 'نَا', waw: 'نُو', yaa: 'نِي' },
    exampleWord: 'نحلة',
    emoji: '🐝',
    sunOrMoon: 'sun',
    wordWithAl: 'النَّحْلَة'
  },
  {
    id: 'haa_round',
    char: 'ه',
    name: 'هاء',
    forms: { isolated: 'ه', start: 'هـ', middle: 'ـهـ', end: 'ـه' },
    sounds: { fatha: 'هَ', kasra: 'هِ', damma: 'هُ' },
    madood: { alif: 'هَا', waw: 'هُو', yaa: 'هِي' },
    exampleWord: 'هرم',
    emoji: '🔺',
    sunOrMoon: 'moon',
    wordWithAl: 'الْهَرَم'
  },
  {
    id: 'waw',
    char: 'و',
    name: 'واو',
    forms: { isolated: 'و', start: 'و', middle: 'ـو', end: 'ـو' },
    sounds: { fatha: 'وَ', kasra: 'وِ', damma: 'وُ' },
    madood: { alif: 'وَا', waw: 'وُو', yaa: 'وِي' },
    exampleWord: 'وردة',
    emoji: '🌹',
    sunOrMoon: 'moon',
    wordWithAl: 'الْوَرْدَة'
  },
  {
    id: 'yaa',
    char: 'ي',
    name: 'ياء',
    forms: { isolated: 'ي', start: 'يـ', middle: 'ـيـ', end: 'ـي' },
    sounds: { fatha: 'يَ', kasra: 'يِ', damma: 'يُ' },
    madood: { alif: 'يَا', waw: 'يُو', yaa: 'يِي' },
    exampleWord: 'يد',
    emoji: '✋',
    sunOrMoon: 'moon',
    wordWithAl: 'الْيَد'
  },
];